trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'mcp-tool'
  LOGIN_SERVER: '<yourregistry>.azurecr.io'
  USERNAME: '<your-registry-username>'
  PASSWORD: '<your-registry-password>'
  PORT: '3000'

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
   versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install Docker
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.10'
  displayName: 'Install Docker'

# Step 3: Build, tag and push the Docker image
- script: |
    docker build -t $(IMAGE_NAME):latest --build-arg PORT=$(PORT) .
    docker tag $(IMAGE_NAME):latest $(LOGIN_SERVER)/$(IMAGE_NAME):latest
    echo $(PASSWORD) | docker login $(LOGIN_SERVER) -u $(USERNAME) --password-stdin
    docker push $(LOGIN_SERVER)/$(IMAGE_NAME):latest
  displayName: 'Build, Tag and Push Docker Image'